version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    volumes:
      - ./options:/etc/rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
